from pydantic import BaseModel, UUID4, Field
from datetime import datetime
from uuid import UUID, uuid4
from typing import List

class Message(BaseModel):
    role: str
    content: str

class Chat(BaseModel):
    chat_id: UUID4 = Field(default_factory=uuid4)  # generated by backend
    chat_name: str = "new chat"
    collection_name: str = ""
    chat_history: List[Message] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.now)
    modified_at: datetime = Field(default_factory=datetime.now)


